# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CCofMinecraft(object):
    def setupUi(self, CCofMinecraft):
        CCofMinecraft.setObjectName("CCofMinecraft")
        CCofMinecraft.setWindowModality(QtCore.Qt.ApplicationModal)
        CCofMinecraft.setEnabled(True)
        CCofMinecraft.resize(960, 480)
        CCofMinecraft.setMinimumSize(QtCore.QSize(960, 480))
        CCofMinecraft.setMaximumSize(QtCore.QSize(960, 480))
        #CCofMinecraft.setSizeGripEnabled(False)
        self.label = QtWidgets.QLabel(CCofMinecraft)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(CCofMinecraft)
        self.line.setGeometry(QtCore.QRect(50, 350, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(CCofMinecraft)
        self.pushButton.setGeometry(QtCore.QRect(800, 130, 131, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(CCofMinecraft)
        self.label_2.setGeometry(QtCore.QRect(30, 370, 131, 21))
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(CCofMinecraft)
        self.lcdNumber.setGeometry(QtCore.QRect(820, 90, 91, 31))
        self.lcdNumber.setStyleSheet("")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Outline)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_3 = QtWidgets.QLabel(CCofMinecraft)
        self.label_3.setGeometry(QtCore.QRect(810, 50, 141, 31))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(CCofMinecraft)
        self.line_2.setGeometry(QtCore.QRect(790, 250, 161, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(CCofMinecraft)
        self.label_4.setGeometry(QtCore.QRect(840, 270, 111, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(CCofMinecraft)
        self.checkBox.setGeometry(QtCore.QRect(30, 400, 131, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(CCofMinecraft)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 420, 151, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(CCofMinecraft)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 440, 161, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.scrollArea = QtWidgets.QScrollArea(CCofMinecraft)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 40, 631, 301))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -554, 608, 1100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(500, 1100))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(30, 450, 54, 12))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(225, 59, 41, 28))
        self.label_12.setObjectName("label_12")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 18, 531, 45))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 3)
        self.radio_allhp_1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_allhp_1.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.radio_allhp_1.setAcceptDrops(False)
        self.radio_allhp_1.setCheckable(True)
        self.radio_allhp_1.setChecked(False)
        self.radio_allhp_1.setAutoRepeat(True)
        self.radio_allhp_1.setAutoExclusive(True)
        self.radio_allhp_1.setObjectName("radio_allhp_1")
        self.gridLayout.addWidget(self.radio_allhp_1, 1, 0, 1, 1)
        self.radio_allhp_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_allhp_2.setAcceptDrops(False)
        self.radio_allhp_2.setAutoExclusive(True)
        self.radio_allhp_2.setObjectName("radio_allhp_2")
        self.gridLayout.addWidget(self.radio_allhp_2, 1, 1, 1, 1)
        self.radio_allhp_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_allhp_3.setAcceptDrops(False)
        self.radio_allhp_3.setAutoExclusive(True)
        self.radio_allhp_3.setObjectName("radio_allhp_3")
        self.gridLayout.addWidget(self.radio_allhp_3, 1, 2, 1, 1)
        self.button_allatk = QtWidgets.QRadioButton(self.layoutWidget)
        self.button_allatk.setStyleSheet("color:blue")
        self.button_allatk.setChecked(True)
        self.button_allatk.setObjectName("button_allatk")
        self.gridLayout.addWidget(self.button_allatk, 1, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 60, 531, 45))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.radio_allatk_1 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radio_allatk_1.setChecked(False)
        self.radio_allatk_1.setAutoRepeat(False)
        self.radio_allatk_1.setAutoExclusive(True)
        self.radio_allatk_1.setObjectName("radio_allatk_1")
        self.gridLayout_2.addWidget(self.radio_allatk_1, 1, 0, 1, 1)
        self.radio_allatk_2 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radio_allatk_2.setAutoExclusive(True)
        self.radio_allatk_2.setObjectName("radio_allatk_2")
        self.gridLayout_2.addWidget(self.radio_allatk_2, 1, 1, 1, 1)
        self.radio_allatk_3 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radio_allatk_3.setAutoExclusive(True)
        self.radio_allatk_3.setObjectName("radio_allatk_3")
        self.gridLayout_2.addWidget(self.radio_allatk_3, 1, 2, 1, 1)
        self.button_allatk_2 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.button_allatk_2.setStyleSheet("color:blue")
        self.button_allatk_2.setChecked(True)
        self.button_allatk_2.setObjectName("button_allatk_2")
        self.gridLayout_2.addWidget(self.button_allatk_2, 1, 3, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget2.setGeometry(QtCore.QRect(21, 102, 531, 45))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 2)
        self.radio_allspeed_1 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_allspeed_1.setChecked(False)
        self.radio_allspeed_1.setAutoRepeat(False)
        self.radio_allspeed_1.setAutoExclusive(True)
        self.radio_allspeed_1.setObjectName("radio_allspeed_1")
        self.gridLayout_3.addWidget(self.radio_allspeed_1, 1, 0, 1, 1)
        self.radio_allspeed_2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_allspeed_2.setAutoExclusive(True)
        self.radio_allspeed_2.setObjectName("radio_allspeed_2")
        self.gridLayout_3.addWidget(self.radio_allspeed_2, 1, 1, 1, 1)
        self.radio_allspeed_3 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_allspeed_3.setAutoExclusive(True)
        self.radio_allspeed_3.setObjectName("radio_allspeed_3")
        self.gridLayout_3.addWidget(self.radio_allspeed_3, 1, 2, 1, 1)
        self.button_allspeed = QtWidgets.QRadioButton(self.layoutWidget2)
        self.button_allspeed.setStyleSheet("color:blue")
        self.button_allspeed.setChecked(True)
        self.button_allspeed.setObjectName("button_allspeed")
        self.gridLayout_3.addWidget(self.button_allspeed, 1, 3, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 144, 531, 45))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 3)
        self.radio_allspeed_4 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radio_allspeed_4.setChecked(False)
        self.radio_allspeed_4.setAutoRepeat(False)
        self.radio_allspeed_4.setAutoExclusive(True)
        self.radio_allspeed_4.setObjectName("radio_allspeed_4")
        self.gridLayout_4.addWidget(self.radio_allspeed_4, 1, 0, 1, 1)
        self.radio_allspeed_5 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radio_allspeed_5.setAutoExclusive(True)
        self.radio_allspeed_5.setObjectName("radio_allspeed_5")
        self.gridLayout_4.addWidget(self.radio_allspeed_5, 1, 1, 1, 1)
        self.radio_allspeed_6 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radio_allspeed_6.setAutoExclusive(True)
        self.radio_allspeed_6.setObjectName("radio_allspeed_6")
        self.gridLayout_4.addWidget(self.radio_allspeed_6, 1, 2, 1, 1)
        self.button_allspeed_2 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.button_allspeed_2.setStyleSheet("color:blue")
        self.button_allspeed_2.setChecked(True)
        self.button_allspeed_2.setObjectName("button_allspeed_2")
        self.gridLayout_4.addWidget(self.button_allspeed_2, 1, 3, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget4.setGeometry(QtCore.QRect(21, 187, 565, 50))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 2, 3)
        self.radio_allweakness_4 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radio_allweakness_4.setObjectName("radio_allweakness_4")
        self.gridLayout_5.addWidget(self.radio_allweakness_4, 1, 2, 2, 1)
        self.radio_allspeed_7 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radio_allspeed_7.setChecked(False)
        self.radio_allspeed_7.setAutoRepeat(False)
        self.radio_allspeed_7.setAutoExclusive(True)
        self.radio_allspeed_7.setObjectName("radio_allspeed_7")
        self.gridLayout_5.addWidget(self.radio_allspeed_7, 2, 0, 1, 1)
        self.radio_allspeed_8 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.radio_allspeed_8.setAutoExclusive(True)
        self.radio_allspeed_8.setObjectName("radio_allspeed_8")
        self.gridLayout_5.addWidget(self.radio_allspeed_8, 2, 1, 1, 1)
        self.button_allspeed_3 = QtWidgets.QRadioButton(self.layoutWidget4)
        self.button_allspeed_3.setStyleSheet("color:blue")
        self.button_allspeed_3.setChecked(True)
        self.button_allspeed_3.setObjectName("button_allspeed_3")
        self.gridLayout_5.addWidget(self.button_allspeed_3, 2, 3, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget5.setGeometry(QtCore.QRect(21, 233, 641, 46))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget5)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_6.addWidget(self.radioButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 2, 1, 1)
        self.battle_cancle = QtWidgets.QRadioButton(self.layoutWidget5)
        self.battle_cancle.setStyleSheet("color:blue")
        self.battle_cancle.setChecked(True)
        self.battle_cancle.setObjectName("battle_cancle")
        self.gridLayout_6.addWidget(self.battle_cancle, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 4, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget6.setGeometry(QtCore.QRect(22, 280, 531, 45))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 3)
        self.radio_allspeed_9 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radio_allspeed_9.setChecked(False)
        self.radio_allspeed_9.setAutoRepeat(False)
        self.radio_allspeed_9.setAutoExclusive(True)
        self.radio_allspeed_9.setObjectName("radio_allspeed_9")
        self.gridLayout_7.addWidget(self.radio_allspeed_9, 1, 0, 1, 1)
        self.radio_allspeed_10 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radio_allspeed_10.setAutoExclusive(True)
        self.radio_allspeed_10.setObjectName("radio_allspeed_10")
        self.gridLayout_7.addWidget(self.radio_allspeed_10, 1, 1, 1, 1)
        self.radio_allspeed_11 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radio_allspeed_11.setAutoExclusive(True)
        self.radio_allspeed_11.setObjectName("radio_allspeed_11")
        self.gridLayout_7.addWidget(self.radio_allspeed_11, 1, 2, 1, 1)
        self.button_allspeed_4 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.button_allspeed_4.setStyleSheet("color:blue")
        self.button_allspeed_4.setChecked(True)
        self.button_allspeed_4.setObjectName("button_allspeed_4")
        self.gridLayout_7.addWidget(self.button_allspeed_4, 1, 3, 1, 1)
        self.layoutWidget7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget7.setGeometry(QtCore.QRect(21, 323, 611, 46))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 2, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 4, 3, 1)
        spacerItem4 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 1, 2, 1)
        self.radio_allspeed_12 = QtWidgets.QRadioButton(self.layoutWidget7)
        self.radio_allspeed_12.setChecked(False)
        self.radio_allspeed_12.setAutoRepeat(False)
        self.radio_allspeed_12.setAutoExclusive(True)
        self.radio_allspeed_12.setObjectName("radio_allspeed_12")
        self.gridLayout_8.addWidget(self.radio_allspeed_12, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 2, 2, 1, 1)
        self.button_allspeed_5 = QtWidgets.QRadioButton(self.layoutWidget7)
        self.button_allspeed_5.setStyleSheet("color:blue")
        self.button_allspeed_5.setChecked(True)
        self.button_allspeed_5.setObjectName("button_allspeed_5")
        self.gridLayout_8.addWidget(self.button_allspeed_5, 2, 3, 1, 1)
        self.layoutWidget8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget8.setGeometry(QtCore.QRect(21, 369, 631, 46))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 0, 1, 4)
        self.radio_allspeed_16 = QtWidgets.QRadioButton(self.layoutWidget8)
        self.radio_allspeed_16.setChecked(False)
        self.radio_allspeed_16.setAutoRepeat(False)
        self.radio_allspeed_16.setAutoExclusive(True)
        self.radio_allspeed_16.setObjectName("radio_allspeed_16")
        self.gridLayout_9.addWidget(self.radio_allspeed_16, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 1, 2, 1, 1)
        self.button_allspeed_7 = QtWidgets.QRadioButton(self.layoutWidget8)
        self.button_allspeed_7.setStyleSheet("color:blue")
        self.button_allspeed_7.setChecked(True)
        self.button_allspeed_7.setObjectName("button_allspeed_7")
        self.gridLayout_9.addWidget(self.button_allspeed_7, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 1, 4, 1, 1)
        self.layoutWidget9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget9.setGeometry(QtCore.QRect(21, 416, 531, 45))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 3)
        self.radio_allspeed_19 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radio_allspeed_19.setChecked(False)
        self.radio_allspeed_19.setAutoRepeat(False)
        self.radio_allspeed_19.setAutoExclusive(True)
        self.radio_allspeed_19.setObjectName("radio_allspeed_19")
        self.gridLayout_10.addWidget(self.radio_allspeed_19, 1, 0, 1, 1)
        self.radio_allspeed_20 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radio_allspeed_20.setAutoExclusive(True)
        self.radio_allspeed_20.setObjectName("radio_allspeed_20")
        self.gridLayout_10.addWidget(self.radio_allspeed_20, 1, 1, 1, 1)
        self.radio_allspeed_21 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radio_allspeed_21.setAutoExclusive(True)
        self.radio_allspeed_21.setObjectName("radio_allspeed_21")
        self.gridLayout_10.addWidget(self.radio_allspeed_21, 1, 2, 1, 1)
        self.button_allspeed_8 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.button_allspeed_8.setStyleSheet("color:blue")
        self.button_allspeed_8.setChecked(True)
        self.button_allspeed_8.setObjectName("button_allspeed_8")
        self.gridLayout_10.addWidget(self.button_allspeed_8, 1, 3, 1, 1)
        self.layoutWidget10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget10.setGeometry(QtCore.QRect(21, 458, 631, 46))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 0, 0, 2, 3)
        spacerItem9 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 1, 1, 2, 1)
        self.radio_cantinwater = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radio_cantinwater.setObjectName("radio_cantinwater")
        self.gridLayout_11.addWidget(self.radio_cantinwater, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 2, 2, 1, 1)
        self.button_cantinwatercancle = QtWidgets.QRadioButton(self.layoutWidget10)
        self.button_cantinwatercancle.setStyleSheet("color:blue")
        self.button_cantinwatercancle.setChecked(True)
        self.button_cantinwatercancle.setObjectName("button_cantinwatercancle")
        self.gridLayout_11.addWidget(self.button_cantinwatercancle, 2, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 2, 4, 1, 1)
        self.layoutWidget11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget11.setGeometry(QtCore.QRect(21, 504, 631, 46))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget11)
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 0, 0, 3, 4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem12, 1, 2, 3, 1)
        spacerItem13 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 2, 1, 2, 1)
        self.radioButton_cantsleep = QtWidgets.QRadioButton(self.layoutWidget11)
        self.radioButton_cantsleep.setObjectName("radioButton_cantsleep")
        self.gridLayout_12.addWidget(self.radioButton_cantsleep, 3, 0, 1, 1)
        self.button_cantsleepcancle = QtWidgets.QRadioButton(self.layoutWidget11)
        self.button_cantsleepcancle.setStyleSheet("color:blue")
        self.button_cantsleepcancle.setChecked(True)
        self.button_cantsleepcancle.setObjectName("button_cantsleepcancle")
        self.gridLayout_12.addWidget(self.button_cantsleepcancle, 3, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem14, 3, 4, 1, 1)
        self.layoutWidget12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget12.setGeometry(QtCore.QRect(21, 550, 631, 46))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget12)
        self.gridLayout_13.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 0, 0, 2, 3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem15, 0, 4, 3, 1)
        spacerItem16 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem16, 1, 1, 2, 1)
        self.radio_itemmakeuneasy = QtWidgets.QRadioButton(self.layoutWidget12)
        self.radio_itemmakeuneasy.setObjectName("radio_itemmakeuneasy")
        self.gridLayout_13.addWidget(self.radio_itemmakeuneasy, 2, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem17, 2, 2, 1, 1)
        self.button_itemmakeuneasycancle = QtWidgets.QRadioButton(self.layoutWidget12)
        self.button_itemmakeuneasycancle.setStyleSheet("color:blue")
        self.button_itemmakeuneasycancle.setChecked(True)
        self.button_itemmakeuneasycancle.setObjectName("button_itemmakeuneasycancle")
        self.gridLayout_13.addWidget(self.button_itemmakeuneasycancle, 2, 3, 1, 1)
        self.layoutWidget13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget13.setGeometry(QtCore.QRect(21, 597, 531, 45))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget13)
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 0, 0, 1, 3)
        self.radio_allspeed_25 = QtWidgets.QRadioButton(self.layoutWidget13)
        self.radio_allspeed_25.setChecked(False)
        self.radio_allspeed_25.setAutoRepeat(False)
        self.radio_allspeed_25.setAutoExclusive(True)
        self.radio_allspeed_25.setObjectName("radio_allspeed_25")
        self.gridLayout_14.addWidget(self.radio_allspeed_25, 1, 0, 1, 1)
        self.radio_allspeed_26 = QtWidgets.QRadioButton(self.layoutWidget13)
        self.radio_allspeed_26.setAutoExclusive(True)
        self.radio_allspeed_26.setObjectName("radio_allspeed_26")
        self.gridLayout_14.addWidget(self.radio_allspeed_26, 1, 1, 1, 1)
        self.radio_allspeed_27 = QtWidgets.QRadioButton(self.layoutWidget13)
        self.radio_allspeed_27.setAutoExclusive(True)
        self.radio_allspeed_27.setObjectName("radio_allspeed_27")
        self.gridLayout_14.addWidget(self.radio_allspeed_27, 1, 2, 1, 1)
        self.button_allspeed_10 = QtWidgets.QRadioButton(self.layoutWidget13)
        self.button_allspeed_10.setStyleSheet("color:blue")
        self.button_allspeed_10.setChecked(True)
        self.button_allspeed_10.setObjectName("button_allspeed_10")
        self.gridLayout_14.addWidget(self.button_allspeed_10, 1, 3, 1, 1)
        self.layoutWidget14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget14.setGeometry(QtCore.QRect(21, 639, 471, 46))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget14)
        self.gridLayout_15.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget14)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 0, 0, 2, 3)
        spacerItem18 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem18, 1, 1, 2, 1)
        self.radio_allspeed_28 = QtWidgets.QRadioButton(self.layoutWidget14)
        self.radio_allspeed_28.setChecked(False)
        self.radio_allspeed_28.setAutoRepeat(False)
        self.radio_allspeed_28.setAutoExclusive(True)
        self.radio_allspeed_28.setObjectName("radio_allspeed_28")
        self.gridLayout_15.addWidget(self.radio_allspeed_28, 2, 0, 1, 1)
        self.radio_allspeed_29 = QtWidgets.QRadioButton(self.layoutWidget14)
        self.radio_allspeed_29.setAutoExclusive(True)
        self.radio_allspeed_29.setObjectName("radio_allspeed_29")
        self.gridLayout_15.addWidget(self.radio_allspeed_29, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem19, 2, 3, 1, 1)
        self.button_allspeed_11 = QtWidgets.QRadioButton(self.layoutWidget14)
        self.button_allspeed_11.setStyleSheet("color:blue")
        self.button_allspeed_11.setChecked(True)
        self.button_allspeed_11.setObjectName("button_allspeed_11")
        self.gridLayout_15.addWidget(self.button_allspeed_11, 2, 4, 1, 1)
        self.layoutWidget15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget15.setGeometry(QtCore.QRect(21, 685, 497, 45))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.layoutWidget15)
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget15)
        self.label_25.setObjectName("label_25")
        self.gridLayout_16.addWidget(self.label_25, 0, 0, 1, 4)
        self.radio_allspeed_31 = QtWidgets.QRadioButton(self.layoutWidget15)
        self.radio_allspeed_31.setChecked(False)
        self.radio_allspeed_31.setAutoRepeat(False)
        self.radio_allspeed_31.setAutoExclusive(True)
        self.radio_allspeed_31.setObjectName("radio_allspeed_31")
        self.gridLayout_16.addWidget(self.radio_allspeed_31, 1, 0, 1, 1)
        self.radio_allspeed_32 = QtWidgets.QRadioButton(self.layoutWidget15)
        self.radio_allspeed_32.setAutoExclusive(True)
        self.radio_allspeed_32.setObjectName("radio_allspeed_32")
        self.gridLayout_16.addWidget(self.radio_allspeed_32, 1, 1, 1, 1)
        self.radio_allspeed_33 = QtWidgets.QRadioButton(self.layoutWidget15)
        self.radio_allspeed_33.setAutoExclusive(True)
        self.radio_allspeed_33.setObjectName("radio_allspeed_33")
        self.gridLayout_16.addWidget(self.radio_allspeed_33, 1, 2, 1, 1)
        self.radio_blind_5 = QtWidgets.QRadioButton(self.layoutWidget15)
        self.radio_blind_5.setObjectName("radio_blind_5")
        self.gridLayout_16.addWidget(self.radio_blind_5, 1, 3, 1, 1)
        self.button_allspeed_12 = QtWidgets.QRadioButton(self.layoutWidget15)
        self.button_allspeed_12.setStyleSheet("color:blue")
        self.button_allspeed_12.setChecked(True)
        self.button_allspeed_12.setObjectName("button_allspeed_12")
        self.gridLayout_16.addWidget(self.button_allspeed_12, 1, 4, 1, 1)
        self.layoutWidget16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget16.setGeometry(QtCore.QRect(21, 727, 471, 46))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget16)
        self.gridLayout_17.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_26.setObjectName("label_26")
        self.gridLayout_17.addWidget(self.label_26, 0, 0, 2, 4)
        spacerItem20 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem20, 1, 1, 2, 1)
        self.radioButton_allrain = QtWidgets.QRadioButton(self.layoutWidget16)
        self.radioButton_allrain.setObjectName("radioButton_allrain")
        self.gridLayout_17.addWidget(self.radioButton_allrain, 2, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem21, 2, 2, 1, 1)
        self.button_allraincancle = QtWidgets.QRadioButton(self.layoutWidget16)
        self.button_allraincancle.setStyleSheet("color:blue")
        self.button_allraincancle.setChecked(True)
        self.button_allraincancle.setObjectName("button_allraincancle")
        self.gridLayout_17.addWidget(self.button_allraincancle, 2, 3, 1, 1)
        self.layoutWidget17 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget17.setGeometry(QtCore.QRect(21, 773, 531, 45))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.layoutWidget17)
        self.gridLayout_18.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget17)
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 0, 0, 1, 3)
        self.radio_allspeed_34 = QtWidgets.QRadioButton(self.layoutWidget17)
        self.radio_allspeed_34.setChecked(False)
        self.radio_allspeed_34.setAutoRepeat(False)
        self.radio_allspeed_34.setAutoExclusive(True)
        self.radio_allspeed_34.setObjectName("radio_allspeed_34")
        self.gridLayout_18.addWidget(self.radio_allspeed_34, 1, 0, 1, 1)
        self.radio_allspeed_35 = QtWidgets.QRadioButton(self.layoutWidget17)
        self.radio_allspeed_35.setAutoExclusive(True)
        self.radio_allspeed_35.setObjectName("radio_allspeed_35")
        self.gridLayout_18.addWidget(self.radio_allspeed_35, 1, 1, 1, 1)
        self.radio_allspeed_36 = QtWidgets.QRadioButton(self.layoutWidget17)
        self.radio_allspeed_36.setAutoExclusive(True)
        self.radio_allspeed_36.setObjectName("radio_allspeed_36")
        self.gridLayout_18.addWidget(self.radio_allspeed_36, 1, 2, 1, 1)
        self.button_allspeed_13 = QtWidgets.QRadioButton(self.layoutWidget17)
        self.button_allspeed_13.setStyleSheet("color:blue")
        self.button_allspeed_13.setChecked(True)
        self.button_allspeed_13.setObjectName("button_allspeed_13")
        self.gridLayout_18.addWidget(self.button_allspeed_13, 1, 3, 1, 1)
        self.layoutWidget18 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget18.setGeometry(QtCore.QRect(22, 815, 562, 53))
        self.layoutWidget18.setObjectName("layoutWidget18")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.layoutWidget18)
        self.gridLayout_19.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.radio_allspeed_37 = QtWidgets.QRadioButton(self.layoutWidget18)
        self.radio_allspeed_37.setChecked(False)
        self.radio_allspeed_37.setAutoRepeat(False)
        self.radio_allspeed_37.setAutoExclusive(True)
        self.radio_allspeed_37.setObjectName("radio_allspeed_37")
        self.gridLayout_19.addWidget(self.radio_allspeed_37, 2, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem22, 1, 3, 2, 1)
        self.button_allspeed_14 = QtWidgets.QRadioButton(self.layoutWidget18)
        self.button_allspeed_14.setStyleSheet("color:blue")
        self.button_allspeed_14.setChecked(True)
        self.button_allspeed_14.setObjectName("button_allspeed_14")
        self.gridLayout_19.addWidget(self.button_allspeed_14, 2, 4, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem23, 2, 1, 1, 1)
        self.radio_allspeed_38 = QtWidgets.QRadioButton(self.layoutWidget18)
        self.radio_allspeed_38.setAutoExclusive(True)
        self.radio_allspeed_38.setObjectName("radio_allspeed_38")
        self.gridLayout_19.addWidget(self.radio_allspeed_38, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget18)
        self.label_28.setObjectName("label_28")
        self.gridLayout_19.addWidget(self.label_28, 0, 0, 1, 1)
        self.layoutWidget19 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget19.setGeometry(QtCore.QRect(21, 861, 531, 45))
        self.layoutWidget19.setObjectName("layoutWidget19")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.layoutWidget19)
        self.gridLayout_20.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget19)
        self.label_29.setObjectName("label_29")
        self.gridLayout_20.addWidget(self.label_29, 0, 0, 1, 3)
        self.radio_allspeed_39 = QtWidgets.QRadioButton(self.layoutWidget19)
        self.radio_allspeed_39.setChecked(False)
        self.radio_allspeed_39.setAutoRepeat(False)
        self.radio_allspeed_39.setAutoExclusive(True)
        self.radio_allspeed_39.setObjectName("radio_allspeed_39")
        self.gridLayout_20.addWidget(self.radio_allspeed_39, 1, 0, 1, 1)
        self.radio_allspeed_40 = QtWidgets.QRadioButton(self.layoutWidget19)
        self.radio_allspeed_40.setAutoExclusive(True)
        self.radio_allspeed_40.setObjectName("radio_allspeed_40")
        self.gridLayout_20.addWidget(self.radio_allspeed_40, 1, 1, 1, 1)
        self.radio_allspeed_41 = QtWidgets.QRadioButton(self.layoutWidget19)
        self.radio_allspeed_41.setAutoExclusive(True)
        self.radio_allspeed_41.setObjectName("radio_allspeed_41")
        self.gridLayout_20.addWidget(self.radio_allspeed_41, 1, 2, 1, 1)
        self.button_allspeed_15 = QtWidgets.QRadioButton(self.layoutWidget19)
        self.button_allspeed_15.setStyleSheet("color:blue")
        self.button_allspeed_15.setChecked(True)
        self.button_allspeed_15.setObjectName("button_allspeed_15")
        self.gridLayout_20.addWidget(self.button_allspeed_15, 1, 3, 1, 1)
        self.layoutWidget20 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget20.setGeometry(QtCore.QRect(20, 898, 583, 108))
        self.layoutWidget20.setObjectName("layoutWidget20")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget20)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget20)
        self.label_32.setObjectName("label_32")
        self.gridLayout_21.addWidget(self.label_32, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem24, 0, 1, 1, 1)
        self.radio_diedimprove_2 = QtWidgets.QRadioButton(self.layoutWidget20)
        self.radio_diedimprove_2.setObjectName("radio_diedimprove_2")
        self.gridLayout_21.addWidget(self.radio_diedimprove_2, 1, 0, 1, 1)
        self.radio_diedimprove_3 = QtWidgets.QRadioButton(self.layoutWidget20)
        self.radio_diedimprove_3.setObjectName("radio_diedimprove_3")
        self.gridLayout_21.addWidget(self.radio_diedimprove_3, 1, 1, 1, 1)
        self.button_diedimprovecancle = QtWidgets.QRadioButton(self.layoutWidget20)
        self.button_diedimprovecancle.setStyleSheet("color:blue")
        self.button_diedimprovecancle.setChecked(True)
        self.button_diedimprovecancle.setObjectName("button_diedimprovecancle")
        self.gridLayout_21.addWidget(self.button_diedimprovecancle, 1, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem25, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_8 = QtWidgets.QLabel(CCofMinecraft)
        self.label_8.setGeometry(QtCore.QRect(630, 10, 141, 21))
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(CCofMinecraft)
        self.textBrowser.setGeometry(QtCore.QRect(630, 30, 151, 421))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(CCofMinecraft)
        self.textBrowser_2.setGeometry(QtCore.QRect(800, 200, 131, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_7 = QtWidgets.QLabel(CCofMinecraft)
        self.label_7.setGeometry(QtCore.QRect(830, 300, 141, 111))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(CCofMinecraft)
        QtCore.QMetaObject.connectSlotsByName(CCofMinecraft)

    def retranslateUi(self, CCofMinecraft):
        _translate = QtCore.QCoreApplication.translate
        CCofMinecraft.setWindowTitle(_translate("CCofMinecraft", "危机合约生成器-秋梨社"))
        self.label.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">[常规合约]</span></p></body></html>"))
        self.pushButton.setText(_translate("CCofMinecraft", "生成数据包"))
        self.label_2.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#0000ff;\">[倍率合约]</span></p></body></html>"))
        self.label_3.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffaa00;\">合约等级</span></p></body></html>"))
        self.label_4.setText(_translate("CCofMinecraft", "制作团队"))
        self.checkBox.setText(_translate("CCofMinecraft", "[x1.5]永夜"))
        self.checkBox_2.setText(_translate("CCofMinecraft", "[x1.8]极限模式"))
        self.checkBox_3.setText(_translate("CCofMinecraft", "[x0.7]死亡不掉落"))
        self.label_12.setText(_translate("CCofMinecraft", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:耐力 </span><span style=\" color:#aa00ff;\">所有敌对生物生命值提高</span></p></body></html>"))
        self.radio_allhp_1.setText(_translate("CCofMinecraft", "[1]提高60%"))
        self.radio_allhp_2.setText(_translate("CCofMinecraft", "[2]提高110%"))
        self.radio_allhp_3.setText(_translate("CCofMinecraft", "[3]提高160%"))
        self.button_allatk.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_6.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:刺激 </span><span style=\" color:#aa00ff;\">所有敌对生物攻击力提高</span></p></body></html>"))
        self.radio_allatk_1.setText(_translate("CCofMinecraft", "[1]提高30%"))
        self.radio_allatk_2.setText(_translate("CCofMinecraft", "[2]提高60%"))
        self.radio_allatk_3.setText(_translate("CCofMinecraft", "[3]提高90%"))
        self.button_allatk_2.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_13.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境：爆发 </span><span style=\" color:#aa00ff;\">所有敌对生物移速增加</span></p></body></html>"))
        self.radio_allspeed_1.setText(_translate("CCofMinecraft", "[1]提高25%"))
        self.radio_allspeed_2.setText(_translate("CCofMinecraft", "[2]提高50%"))
        self.radio_allspeed_3.setText(_translate("CCofMinecraft", "[3]提高75%"))
        self.button_allspeed.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_9.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标:侵蚀 </span><span style=\" color:#aa00ff;\">生命值上限降低</span></p></body></html>"))
        self.radio_allspeed_4.setText(_translate("CCofMinecraft", "[1]4"))
        self.radio_allspeed_5.setText(_translate("CCofMinecraft", "[3]8"))
        self.radio_allspeed_6.setText(_translate("CCofMinecraft", "[6]16"))
        self.button_allspeed_2.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_10.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境：虚弱因子 </span><span style=\" color:#aa00ff;\">伤害降低以及挖掘疲劳</span></p></body></html>"))
        self.radio_allweakness_4.setText(_translate("CCofMinecraft", "[4]伤害降低30%\n"
"并获得挖掘疲劳1级"))
        self.radio_allspeed_7.setText(_translate("CCofMinecraft", "[1]伤害降低15%"))
        self.radio_allspeed_8.setText(_translate("CCofMinecraft", "[2]伤害效果降低30%"))
        self.button_allspeed_3.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_11.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标：殊死搏斗 </span><span style=\" color:#aa00ff;\">你无法自然恢复生命</span></p></body></html>"))
        self.radioButton.setText(_translate("CCofMinecraft", "[5]选择"))
        self.battle_cancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_15.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境：亡灵觉醒 </span><span style=\" color:#aa00ff;\">亡灵类生物攻击力、生命值提高</span></p></body></html>"))
        self.radio_allspeed_9.setText(_translate("CCofMinecraft", "[1]40%、50%"))
        self.radio_allspeed_10.setText(_translate("CCofMinecraft", "[3]80%、100%"))
        self.radio_allspeed_11.setText(_translate("CCofMinecraft", "[5]120%、150%"))
        self.button_allspeed_4.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_16.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:隐形爆破  </span><span style=\" color:#aa00ff;\">苦力怕增强</span></p></body></html>"))
        self.radio_allspeed_12.setText(_translate("CCofMinecraft", "[2]苦力怕隐形,无声"))
        self.button_allspeed_5.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_17.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:灵敏嗅觉 </span><span style=\" color:#aa00ff;\">敌对生物发现玩家距离提升</span></p></body></html>"))
        self.radio_allspeed_16.setText(_translate("CCofMinecraft", "[1]提升175"))
        self.button_allspeed_7.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_18.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标：龙吟 </span><span style=\" color:#aa00ff;\">[末影龙]伤害、血量提升</span></p></body></html>"))
        self.radio_allspeed_19.setText(_translate("CCofMinecraft", "[1]50%、50%"))
        self.radio_allspeed_20.setText(_translate("CCofMinecraft", "[2]100%、100%"))
        self.radio_allspeed_21.setText(_translate("CCofMinecraft", "[3]150%、150%"))
        self.button_allspeed_8.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_30.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:思想钢印 </span><span style=\" color:#aa00ff;\">在水中受到中毒效果</span></p></body></html>"))
        self.radio_cantinwater.setText(_translate("CCofMinecraft", "[1]选择"))
        self.button_cantinwatercancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_21.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">削弱:失眠 </span><span style=\" color:#aa00ff;\">你无法入睡，与永夜冲突</span></p></body></html>"))
        self.radioButton_cantsleep.setText(_translate("CCofMinecraft", "[1]选择"))
        self.button_cantsleepcancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_22.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:易碎物品 </span><span style=\" color:#aa00ff;\">死亡后掉落物品消失</span></p></body></html>"))
        self.radio_itemmakeuneasy.setText(_translate("CCofMinecraft", "[2]选择"))
        self.button_itemmakeuneasycancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_23.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">模式:难度选择 </span><span style=\" color:#aa00ff;\">不选默认普通</span></p></body></html>"))
        self.radio_allspeed_25.setText(_translate("CCofMinecraft", "[0]简单"))
        self.radio_allspeed_26.setText(_translate("CCofMinecraft", "[1]普通"))
        self.radio_allspeed_27.setText(_translate("CCofMinecraft", "[2]困难"))
        self.button_allspeed_10.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_24.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标:沉重武器 </span><span style=\" color:#aa00ff;\">攻击速度降低</span></p></body></html>"))
        self.radio_allspeed_28.setText(_translate("CCofMinecraft", "[1]0.3次每秒"))
        self.radio_allspeed_29.setText(_translate("CCofMinecraft", "[2]0.6次每秒"))
        self.button_allspeed_11.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_25.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标:失明 </span><span style=\" color:#aa00ff;\">血量低于一定血量时失明</span></p></body></html>"))
        self.radio_allspeed_31.setText(_translate("CCofMinecraft", "[1]低于6"))
        self.radio_allspeed_32.setText(_translate("CCofMinecraft", "[2]低于12"))
        self.radio_allspeed_33.setText(_translate("CCofMinecraft", "[3]低于16"))
        self.radio_blind_5.setText(_translate("CCofMinecraft", "[5]低于24"))
        self.button_allspeed_12.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_26.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:暴雨 </span><span style=\" color:#aa00ff;\">天气恒为雷雨</span></p></body></html>"))
        self.radioButton_allrain.setText(_translate("CCofMinecraft", "[2]选择"))
        self.button_allraincancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_27.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">目标:生命限制 </span><span style=\" color:#aa00ff;\">限制复活次数</span></p></body></html>"))
        self.radio_allspeed_34.setText(_translate("CCofMinecraft", "[1]复活20次"))
        self.radio_allspeed_35.setText(_translate("CCofMinecraft", "[2]复活20次"))
        self.radio_allspeed_36.setText(_translate("CCofMinecraft", "[3]复活15次"))
        self.button_allspeed_13.setText(_translate("CCofMinecraft", "取消选择"))
        self.radio_allspeed_37.setText(_translate("CCofMinecraft", "[1]速度2"))
        self.button_allspeed_14.setText(_translate("CCofMinecraft", "取消选择"))
        self.radio_allspeed_38.setText(_translate("CCofMinecraft", "[2]速度2、隐身"))
        self.label_28.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">环境:节肢动物强化 </span><span style=\" color:#aa00ff;\">蜘蛛、洞穴蜘蛛获得效果</span></p></body></html>"))
        self.label_29.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">削弱:沉重 </span><span style=\" color:#aa00ff;\">玩家移动速度减慢</span></p></body></html>"))
        self.radio_allspeed_39.setText(_translate("CCofMinecraft", "[1]15%"))
        self.radio_allspeed_40.setText(_translate("CCofMinecraft", "[2]25%"))
        self.radio_allspeed_41.setText(_translate("CCofMinecraft", "[3]40%"))
        self.button_allspeed_15.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_32.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-weight:600;\">特化:亡灵 </span></p></body></html>"))
        self.radio_diedimprove_2.setText(_translate("CCofMinecraft", "[2]僵尸类血量提升至1000%，\n"
"移动速度降低50%，伤害降低20%\n"
"骷髅类伤害提升600%，\n"
"移动速度降低30%，血量降低40%"))
        self.radio_diedimprove_3.setText(_translate("CCofMinecraft", "[3]僵尸类血量提升至1000%，\n"
"移动速度降低30%，伤害降低10%\n"
"骷髅类伤害提升600%，\n"
"移动速度降低20%，血量降低20%"))
        self.button_diedimprovecancle.setText(_translate("CCofMinecraft", "取消选择"))
        self.label_8.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ffaa00;\">[已选合约]</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("CCofMinecraft", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("CCofMinecraft", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ffaa00;\">[秋梨社]</span></p></body></html>"))

